package com.cesar.pokedex.data.repository

import com.cesar.pokedex.data.local.dao.PokemonDao
import com.cesar.pokedex.data.local.dao.TeamDao
import com.cesar.pokedex.data.local.entity.PokemonEntity
import com.cesar.pokedex.data.local.entity.PokemonTeamEntity
import com.cesar.pokedex.domain.model.PokemonTeam
import io.mockk.coEvery
import io.mockk.coJustRun
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test

class TeamRepositoryImplTest {

    private val teamDao: TeamDao = mockk()
    private val pokemonDao: PokemonDao = mockk()
    private lateinit var repository: TeamRepositoryImpl

    @Before
    fun setUp() {
        coJustRun { teamDao.updateTeam(any()) }
        coJustRun { teamDao.deleteTeam(any()) }
        every { teamDao.getAllTeams() } returns flowOf(emptyList())
        repository = TeamRepositoryImpl(teamDao, pokemonDao)
    }

    // region addMember

    @Test
    fun `addMember addsIdWhenTeamHasCapacity`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Team", pokemonIds = listOf(1, 2, 3))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.addMember(1L, 4)

        coVerify { teamDao.updateTeam(entity.copy(pokemonIds = listOf(1, 2, 3, 4))) }
    }

    @Test
    fun `addMember silentlyIgnoresWhenTeamHasSixMembers`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Team", pokemonIds = listOf(1, 2, 3, 4, 5, 6))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.addMember(1L, 7)

        coVerify(exactly = 0) { teamDao.updateTeam(any()) }
    }

    @Test
    fun `addMember allowsUpToSixMembersExactly`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Team", pokemonIds = listOf(1, 2, 3, 4, 5))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.addMember(1L, 6)

        coVerify { teamDao.updateTeam(entity.copy(pokemonIds = listOf(1, 2, 3, 4, 5, 6))) }
    }

    @Test
    fun `addMember silentlyIgnoresDuplicatePokemon`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Team", pokemonIds = listOf(1, 4, 7))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.addMember(1L, 4)

        coVerify(exactly = 0) { teamDao.updateTeam(any()) }
    }

    @Test
    fun `addMember doesNothingWhenTeamNotFound`() = runTest {
        coEvery { teamDao.getTeamById(99L) } returns null

        repository.addMember(99L, 1)

        coVerify(exactly = 0) { teamDao.updateTeam(any()) }
    }

    // endregion

    // region removeMember

    @Test
    fun `removeMember removesIdFromList`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Team", pokemonIds = listOf(1, 4, 25))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.removeMember(1L, 4)

        coVerify { teamDao.updateTeam(entity.copy(pokemonIds = listOf(1, 25))) }
    }

    @Test
    fun `removeMember doesNothingWhenTeamNotFound`() = runTest {
        coEvery { teamDao.getTeamById(99L) } returns null

        repository.removeMember(99L, 1)

        coVerify(exactly = 0) { teamDao.updateTeam(any()) }
    }

    @Test
    fun `removeMember isNoOpWhenIdNotInList`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Team", pokemonIds = listOf(1, 4))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.removeMember(1L, 999)

        coVerify { teamDao.updateTeam(entity.copy(pokemonIds = listOf(1, 4))) }
    }

    // endregion

    // region createTeam

    @Test
    fun `createTeam returnsAutoGeneratedId`() = runTest {
        coEvery { teamDao.insertTeam(any()) } returns 42L

        val result = repository.createTeam("My Team")

        assertEquals(42L, result)
    }

    // endregion

    // region deleteTeam

    @Test
    fun `deleteTeam delegatesToDao`() = runTest {
        repository.deleteTeam(5L)

        coVerify { teamDao.deleteTeam(5L) }
    }

    // endregion

    // region getAllTeams

    @Test
    fun `getAllTeams mapsDaoEntitiesToDomainModels`() = runTest {
        val pokemonEntity = PokemonEntity(id = 1, name = "Bulbasaur", imageUrl = "https://example.com/1.png", types = listOf("Grass"))
        val teamEntity = PokemonTeamEntity(id = 1L, name = "My Team", pokemonIds = listOf(1))
        every { teamDao.getAllTeams() } returns flowOf(listOf(teamEntity))
        coEvery { pokemonDao.getPokemonById(1) } returns pokemonEntity
        repository = TeamRepositoryImpl(teamDao, pokemonDao)

        val result: List<PokemonTeam> = repository.getAllTeams().first()

        assertEquals(1, result.size)
        assertEquals("My Team", result[0].name)
        assertEquals(1, result[0].members.size)
        assertEquals("Bulbasaur", result[0].members[0].name)
    }

    @Test
    fun `getAllTeams excludesMembersNotFoundInPokemonDao`() = runTest {
        val pokemonEntity = PokemonEntity(id = 1, name = "Bulbasaur", imageUrl = "https://example.com/1.png", types = listOf("Grass"))
        val teamEntity = PokemonTeamEntity(id = 1L, name = "My Team", pokemonIds = listOf(1, 999))
        every { teamDao.getAllTeams() } returns flowOf(listOf(teamEntity))
        coEvery { pokemonDao.getPokemonById(1) } returns pokemonEntity
        coEvery { pokemonDao.getPokemonById(999) } returns null
        repository = TeamRepositoryImpl(teamDao, pokemonDao)

        val result: List<PokemonTeam> = repository.getAllTeams().first()

        assertEquals(1, result[0].members.size)
        assertEquals("Bulbasaur", result[0].members[0].name)
    }

    // endregion

    // region renameTeam

    @Test
    fun `renameTeam updatesNameWhenTeamExists`() = runTest {
        val entity = PokemonTeamEntity(id = 1L, name = "Old Name", pokemonIds = listOf(1, 2))
        coEvery { teamDao.getTeamById(1L) } returns entity

        repository.renameTeam(1L, "New Name")

        coVerify { teamDao.updateTeam(entity.copy(name = "New Name")) }
    }

    @Test
    fun `renameTeam doesNothingWhenTeamNotFound`() = runTest {
        coEvery { teamDao.getTeamById(99L) } returns null

        repository.renameTeam(99L, "New Name")

        coVerify(exactly = 0) { teamDao.updateTeam(any()) }
    }

    // endregion
}
